### ISSUE TITLE
[BUG] Cannot run test in debug mode on Visual Studio Code February 2025 (version 1.98)

### ISSUE THREAD

**Issue by szendihorvathjozsef** [jest-community/vscode-jest#1221]
Hi,

**Describe the bug**
I have updated my Visual Studio Code to version 1.98 and I have experienced that I cannot run a test case in debub mode. I have tried with doing a clean installation of Visual Studio Code version 1.98 and I have faced with same issue. Uninstalling version 1.98 and installing version 1.97 back solved my issue. So perhaps vscode-jest is not yet compatible in some way with 1.98.

**To Reproduce**
1. Go to one of your test file
2. Right click on test options
3. Choose Debug Test

**Expected behavior**
I would expect that Debug Test is functional as on earlier Visual Studio Code versions.

**Screenshots**

![Image](https://github.com/user-attachments/assets/8eff319b-f8ba-45d9-bfe9-58e31628358c)

**Environment (please complete the following information):**
- vscode-jest version: 6.4.0
- `node -v`: v22.11.0
- `npm -v`: 10.9.0
- jest version: 29.7.0
- your vscode-jest setting: nothing specific
- Operating system: Windows 11

**Prerequisite**
Nx is being used as central tool to launch tests for specific projects.

- are you able to run jest from the command line? Yes, I'm able to do.
- where do you run jest CLI from? From the root of the project
- how do you run your tests from the command line? npx nx run xxxx:test, it launched the Jest CLI with specific arguments defined in the Nx project.json and nx.json

**Additional context**
I have not seen this issue before and unfortunately It does not give me any meaningful information regarding the exact problem.

**Comment by evilguest** [comment]
Confirm - same behavior on my end.

**Comment by paulmarchis** [comment]
Confirm also. The error is reproducible when debugging the test
`[error] item d:\example\example.test.js failed to debug: {}.`

**Comment by lostfields** [comment]
Same. I tried the `jest.jestCommandLine` and noticed a different behaviour from running the tests and debugging the tests. 

If I set `jest.jestCommandLine": "npx jest"` the tests are running as normal, but once I try to debug it fails with this:

```
cd d:\\source\\workspace ; /usr/bin/env 'NODE_OPTIONS= --require "c:/Users/anonymous/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.js"  --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS=:::{"inspectorIpc":"\\\\.\\pipe\\node-cdp.xyz.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\anonymous\\AppData\\Local\\Temp\\node-debug-callback-xyz"}' C:\\Program\ Files\\nodejs\\node.exe .\\npx jest --runInBand --watchAll=false --testNamePattern route\ /my tests\$ --runTestsByPath D:\\source\\workspace\\src\\test\\mytest.test.ts
Debugger attached.
Waiting for the debugger to disconnect...
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'D:\source\worksace\npx'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
```
Notice the part `C:\\Program\ Files\\nodejs\\node.exe .\\npx jest --runInBand`

**Comment by connectdotz** [comment]
Hmm... I couldn’t reproduce this on my Mac. Is this issue only happening on Windows? Has anyone else seen it on other platforms?

**Comment by rizwanfhm** [comment]
I had a similar issue using the extension on my Mac and solved with the following:

1. `which npx` from the root of my project
2. set `jest.jestCommandLine` to be this 

fwiw I had used `homebrew` to install to install `node` so my config ended up being

```
"jest.jestCommandLine": "/opt/homebrew/bin/npx jest",
```

**Comment by connectdotz** [comment]
I tested this again on Windows using VS Code 1.98.2, but I’m still unable to reproduce the issue. This makes me suspect it might be tied to something specific in the repo setup. If anyone is still encountering the problem, could you share a minimal reproducible example or sample repo? I’d be happy to take a closer look. Thanks!

**Comment by ipax77** [comment]
@connectdotz I created a sample repo for it:  [jest-plugin-test](https://github.com/ipax77/jest-plugin-test/tree/main), it has some special settings but it worked with vscode pre 1.98.2.

**Comment by connectdotz** [comment]
@ipax77 Thanks for the repo!😃 I think I found the culprit and will patch it soon.

**Comment by lostfields** [comment]
When will this be released? Still version 6.4.0 in marketplace and this is a big blocker for me.

**Comment by connectdotz** [comment]
I’ll likely do a pre-release later this week just to be safe. I’ll ping you all once it’s ready for testing. Thanks for your patience!

**Comment by connectdotz** [comment]
[v.6.4.1-pre-release](https://github.com/jest-community/vscode-jest/releases/tag/v6.4.1-next) is available now, please feel free to git it a try and let us know if it fixed your issue.

**Comment by ipax77** [comment]
For me v6.4.1 is working, for the sample project as well as my real world app, thank you!
